### ISSUE TITLE
[BUG]  size mismatch, got 4096, 4096x512,64

### ISSUE THREAD

**Issue by amy58328** [kyegomez/PALI3#12]
I want to train the SigLIP model first.
So first run train_vit_siglip.py
But I ran into a matrix dimension mismatch.
I would like to ask if there is any solution to this problem.

**To Reproduce**
I was running train_vit_silip.py and ran into the 'VitModel' object has no attribute 'to' problem, 
so I added the new red boxed section to the Vitmodel to slove the problem, 
other than that I didn't change any code.
![image](https://github.com/kyegomez/PALI3/assets/43245005/7603876b-d440-421d-b389-a9cf85d7be19)

**Screenshots**
![螢幕擷取畫面 2024-01-05 125238](https://github.com/kyegomez/PALI3/assets/43245005/d6d66471-ec43-4d02-b07f-86c0c9ece2e9)

**Comment by kyegomez** [comment]
@amy58328, hey! Thanks a lot for submitting the issue. It appears that the train signal logic was never optimized, which is something I hadn't considered before. I appreciate you bringing it up. Would you mind taking a look at it and making the necessary fixes? Once you're done, please submit a pull request so that we can review and incorporate

**Comment by amy58328** [comment]
If I solve this problem, I'll be happy to make a pull  request.
But I would like to ask you if you know the cause of matrix dimension mismatch.
Maybe you can give me some ideas, help me fix it

**Comment by kyegomez** [comment]
@amy58328 line 200 in the error stack trace
